# Generated by Django 4.2.4 on 2025-06-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_weighted_ranking', models.BooleanField(default=False)),
                ('display_seq', models.CharField(db_index=True, default='year-semester-w01', max_length=50)),
                ('solution_release_policy', models.CharField(choices=[('NEVER', '不公布'), ('IMMEDIATE', '立即公布'), ('AFTER_CONTEST', '結束後公布')], default='NEVER', max_length=20)),
            ],
            options={
                'ordering': ('-display_seq',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('judge_id', models.IntegerField(default=0, help_text='Judge0 Extra CE identifier')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MySysOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.TextField(blank=True, null=True)),
                ('option_value', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_permanent', models.BooleanField(default=True, help_text='永久顯示，否則會依據到期時間停止顯示')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_seq', models.CharField(default='10-10', help_text='顯示的順序，請依據章節主題的講授順序或難易度排列', max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id_seq', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_output_description', models.TextField(blank=True, null=True)),
                ('std_input', models.TextField(blank=True, null=True)),
                ('std_output', models.TextField(blank=True, null=True)),
                ('sample_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='problems', to='app_management.problemcategory')),
                ('language', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='app_management.language')),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prblm_in_contest', models.CharField(default='q1', max_length=25)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.problem')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='app_management.ContestProblem', to='app_management.problem'),
        ),
    ]
