# Generated by Django 4.2.4 on 2025-06-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_contest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='password',
        ),
    ]
