# Generated by Django 4.2.4 on 2026-06-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_remove_contest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='input_output_description',
        ),
    ]
