# Generated by Django 4.2.4 on 2026-06-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0004_remove_problem_input_output_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('contest', 'id_prblm_in_contest')},
        ),
    ]
