# Generated by Django 4.2.4 on 2025-06-12 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('judge_compile_output', models.TextField(blank=True, null=True)),
                ('judge_status_description', models.CharField(max_length=20)),
                ('judge_status', models.IntegerField(db_index=True, default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.problem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ContestRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('submission_info', models.JSONField(default=dict)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.contest')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('submitted_by', 'contest', 'problem'), name='unique_submission'),
        ),
    ]
