# Generated by Django 4.2.4 on 2025-10-12 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='登入IP位址', max_length=50)),
                ('session_key', models.CharField(blank=True, help_text='Session Key', max_length=40, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='登入時間')),
                ('user_agent', models.TextField(blank=True, help_text='瀏覽器資訊', null=True)),
                ('is_staff_login', models.BooleanField(default=False, help_text='是否為管理員登入')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登入歷史記錄',
                'verbose_name_plural': '登入歷史記錄',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='app_account_user_id_908328_idx'), models.Index(fields=['-login_time'], name='app_account_login_t_a2bcaf_idx'), models.Index(fields=['ip', '-login_time'], name='app_account_ip_2b0c64_idx')],
            },
        ),
    ]
