# Generated by Django 4.2.4 on 2025-10-13 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='登出IP位址', max_length=50)),
                ('session_key', models.CharField(blank=True, help_text='Session Key', max_length=40, null=True)),
                ('logout_time', models.DateTimeField(auto_now_add=True, help_text='登出時間')),
                ('user_agent', models.TextField(blank=True, help_text='瀏覽器資訊', null=True)),
                ('is_staff_logout', models.BooleanField(default=False, help_text='是否為管理員登出')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logout_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登出歷史記錄',
                'verbose_name_plural': '登出歷史記錄',
                'ordering': ['-logout_time'],
                'indexes': [models.Index(fields=['user', '-logout_time'], name='app_account_user_id_483b3e_idx'), models.Index(fields=['-logout_time'], name='app_account_logout__d2f3b1_idx'), models.Index(fields=['ip', '-logout_time'], name='app_account_ip_fe04c0_idx')],
            },
        ),
    ]
